version: '3'

networks:
  # enable connection with Traefik
  traefik:
    external: true

services:
  portainer:
    container_name: "portainer-exemplo-web"
    image: portainer/portainer-ce:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./portainer_data:/data
    networks:
      - traefik    
    labels:
      # The labels are usefull for Traefik only
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Get the routes from http
      #- "traefik.http.routers.portainer-exemplo.rule=Host(`${DOMAIN}`) && PathPrefix(`/DOMAINPATH`)"
      - "traefik.http.routers.portainer-exemplo.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.portainer-exemplo.entrypoints=web"
      # Redirect these routes to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer-exemplo.middlewares=redirect-to-https@docker"
      # Get the routes from https
      #- "traefik.http.routers.portainer-exemplo-secured.rule=Host(`${DOMAIN}`) && PathPrefix(`/DOMAINPATH`)"
      - "traefik.http.routers.portainer-exemplo-secured.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.portainer-exemplo-secured.entrypoints=web-secure"
      # Apply autentificiation with http challenge
      - "traefik.http.routers.portainer-exemplo-secured.tls=true"
      - "traefik.http.routers.portainer-exemplo-secured.tls.certresolver=myhttpchallenge"
      # Get service on 9000 port
      - "traefik.http.routers.portainer-vieira.service=portainer-exemplo"
      - "traefik.http.services.portainer-exemplo.loadbalancer.server.port=9000"
