version: '3'

networks:
  # enable connection with Traefik
  traefik:
    external: true

services:
  nginx:
    container_name: "portainer-exemplo-web"
    image: portainer/portainer-ce:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - portainer_data:/data
    networks:
      - traefik    
    labels:
      # The labels are usefull for Traefik only
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Get the routes from http
      #- "traefik.http.routers.site-portainer.rule=Host(`${DOMAIN}`) && PathPrefix(`/DOMAINPATH`)"
      - "traefik.http.routers.site-portainer.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.site-portainer.entrypoints=web"
      # Redirect these routes to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.site-portainer.middlewares=redirect-to-https@docker"
      # Get the routes from https
      #- "traefik.http.routers.site-portainer-secured.rule=Host(`${DOMAIN}`) && PathPrefix(`/DOMAINPATH`)"
      - "traefik.http.routers.site-portainer-secured.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.site-portainer-secured.entrypoints=web-secure"
      # Apply autentificiation with http challenge
      - "traefik.http.routers.site-portainer-secured.tls=true"
      - "traefik.http.routers.site-portainer-secured.tls.certresolver=myhttpchallenge"